-- MySQL Script generated by MySQL Workbench
-- Wed Jan 24 08:36:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema flash
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `flash` ;

-- -----------------------------------------------------
-- Schema flash
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flash` DEFAULT CHARACTER SET utf8 ;
USE `flash` ;

-- -----------------------------------------------------
-- Table `flash`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flash`.`endereco` ;

CREATE TABLE IF NOT EXISTS `flash`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flash`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flash`.`usuario` ;

CREATE TABLE IF NOT EXISTS `flash`.`usuario` (
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(200) NOT NULL,
  `tipo_acesso` ENUM('fisica', 'juridica', 'funcionario', 'administrador') NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `sexo` ENUM('f', 'm') NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `endereco` INT NOT NULL,
  INDEX `endereco_idx` (`endereco` ASC),
  PRIMARY KEY (`cpf`),
  CONSTRAINT `endereco`
    FOREIGN KEY (`endereco`)
    REFERENCES `flash`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `flash`.`unidade_tratamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flash`.`unidade_tratamento` ;

CREATE TABLE IF NOT EXISTS `flash`.`unidade_tratamento` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `administrador` VARCHAR(15) NOT NULL,
  `endereco` INT NOT NULL,
  PRIMARY KEY (`codigo`, `endereco`),
  INDEX `adm_idx` (`administrador` ASC),
  INDEX `end_idx` (`endereco` ASC),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  CONSTRAINT `adm`
    FOREIGN KEY (`administrador`)
    REFERENCES `flash`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `end`
    FOREIGN KEY (`endereco`)
    REFERENCES `flash`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `flash`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flash`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `flash`.`veiculo` (
  `placa` CHAR(7) NOT NULL,
  `ano` CHAR(4) NOT NULL,
  `modelo` VARCHAR(25) NOT NULL,
  `volume_maximo` FLOAT NOT NULL,
  `carga_maxima` FLOAT NOT NULL,
  `funcionario` VARCHAR(15) NOT NULL,
  `origem` INT NOT NULL,
  `destino` INT NOT NULL,
  PRIMARY KEY (`placa`),
  INDEX `veiculo_ibfk_5_idx` (`destino` ASC),
  INDEX `veiculo_ibfk_4_idx` (`origem` ASC),
  INDEX `funcionario_idx` (`funcionario` ASC),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC),
  CONSTRAINT `veiculo_ibfk_4`
    FOREIGN KEY (`origem`)
    REFERENCES `flash`.`unidade_tratamento` (`codigo`),
  CONSTRAINT `veiculo_ibfk_5`
    FOREIGN KEY (`destino`)
    REFERENCES `flash`.`unidade_tratamento` (`codigo`),
  CONSTRAINT `funcionario`
    FOREIGN KEY (`funcionario`)
    REFERENCES `flash`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `flash`.`encomenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flash`.`encomenda` ;

CREATE TABLE IF NOT EXISTS `flash`.`encomenda` (
  `codigo_rastreio` CHAR(14) NOT NULL,
  `peso` FLOAT NOT NULL,
  `volume` FLOAT NOT NULL,
  `cliente` VARCHAR(15) NOT NULL,
  `estado` ENUM('POSTADO', 'TRANSPORTE', 'ENTREGUE', 'CANCELADO') NOT NULL,
  `veiculo` CHAR(7) NOT NULL,
  `unidade_tratamento` INT NOT NULL,
  `destino` INT NOT NULL,
  PRIMARY KEY (`codigo_rastreio`),
  INDEX `veiculo` (`veiculo` ASC),
  INDEX `unidadeTrat` (`unidade_tratamento` ASC),
  INDEX `cliente_idx` (`cliente` ASC),
  INDEX `endereco_idx` (`destino` ASC),
  UNIQUE INDEX `codigo_rastreio_UNIQUE` (`codigo_rastreio` ASC),
  CONSTRAINT `veiculo`
    FOREIGN KEY (`veiculo`)
    REFERENCES `flash`.`veiculo` (`placa`),
  CONSTRAINT `unidade`
    FOREIGN KEY (`unidade_tratamento`)
    REFERENCES `flash`.`unidade_tratamento` (`codigo`),
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `flash`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `destino`
    FOREIGN KEY (`destino`)
    REFERENCES `flash`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
